Disable opentype svg for stable builds
There seems to be some kind of issue with a define not
being set on stable builds.

This is perhaps due to not using system freetype on stable
builds. The error is below.

third_party/skia/src/ports/SkFontHost_FreeType.cpp:1010:2: \
error: "FT_CONFIG_OPTION_SVG not on"