d/rules: Add hack to fix blink fallthrough build issue
I'm not sure what's changed between releases, or where
the issue lies exactly, but we can do a hacky fix to the
affected generated files (inside out/Release).

Use the rules file to test for and remove any aberrant
instances of the '[[fallthrough]]' notation which cause
(multiple) build errors of the sort below :-

gen/third_party/blink/renderer/core/css/css_property_names.cc:106:7:\
 error: fallthrough annotation does not directly precede switch label
  106 |       [[fallthrough]];
      |       ^

This is a hack which requires the build process to be
re-started after things error out (this may happen
multiple times).