Disable widevine
Widevine is disable due to build errors which I was unable to fix :-

../../chrome/common/chrome_paths.cc:380:5:
error: function-like macro
'BUILDFLAG_INTERNAL_BUNDLE_WIDEVINE_CDM_COMPONENT' is not defined